'use strict';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const COLORS=['lavender','mint','peach','blue','pink','yellow'];
const SCORE={vote:1,survive:2,bonus:1};
const defaults={difficulty:'mixed',imposters:1,clueRounds:2,tellRole:true,voting:false,scores:true,haptics:false,hold:false,bonus:true,useNames:true};
let db={categories:[],pairs:[]},page='home',back='home',query='',round=null,timer=null,revealTimer=null,nameTimer=null,time=120,toastTimer;
let state=load();
// Names are always collected first; old saved settings cannot hide the name fields.
state.settings.useNames=true;state.settings.tellRole=true;state.settings.voting=false;
function load(){try{let s=JSON.parse(localStorage.getItem('imposter-v2')||'{}'),players=Array.isArray(s.players)?s.players:[];if(players.length<3)players=Array.from({length:3},()=>({id:id(),name:'',score:0}));return{settings:{...defaults,...s.settings},players:players.slice(0,15).map((p,i)=>({id:p.id||id(),name:String(p.name||'').slice(0,24),score:+p.score||0,color:COLORS[i%6]})),categories:Array.isArray(s.categories)?s.categories:null,history:Array.isArray(s.history)?s.history:[],packs:Array.isArray(s.packs)?s.packs:[],round:+s.round||0};}catch{return{settings:{...defaults},players:Array.from({length:3},(_,i)=>({id:id(),name:'',score:0,color:COLORS[i%6]})),categories:null,history:[],packs:[],round:0};}}
function save(){try{localStorage.setItem('imposter-v2',JSON.stringify(state));}catch{}}
function id(){return crypto.randomUUID?.()||Math.random().toString(36).slice(2)}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function name(p){return p.name||`Player ${state.players.indexOf(p)+1}`}
function namedPlayers(){return state.players.filter(p=>p.name.trim()).length}
function allPlayersNamed(){return namedPlayers()>=3}
function avatar(p,large=false){let n=name(p),seed=encodeURIComponent(n),src=p.name.trim()?`https://api.dicebear.com/10.x/adventurer-neutral/svg?seed=${seed}`:'./blankpfp.jpg';return `<span class="avatar ${p.color} ${large?'large':''}">${esc(n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase())}<img src="${src}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()"></span>`}
function btn(action,text,kind='primary',attrs=''){return `<button class="${kind}" data-action="${action}" ${attrs}>${text}</button>`}
function toggle(k,title,sub=''){return `<div class="setting-row"><div><strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</div><button class="switch" data-toggle="${k}" role="switch" aria-checked="${!!state.settings[k]}"></button></div>`}
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),2500)}
function pairs(){return [...db.pairs,...state.packs.flatMap(p=>p.pairs.map((x,i)=>({...x,id:`${p.id}:${i}`,category:p.id})))];}
function cats(){return [...db.categories,...state.packs.map(p=>({id:p.id,name:p.name,emoji:'✨'}))]}
function eligible(){return pairs().filter(x=>state.categories.includes(x.category)&&(state.settings.difficulty==='mixed'||x.difficulty===state.settings.difficulty))}
function heading(a,b,c=''){return `<div class="page-heading"><div><div class="eyebrow">${a}</div><h1>${b}</h1>${c?`<p>${c}</p>`:''}</div></div>`}
function render(){let views={home,setup,categories,pass,word,discussion,votepass,vote,votes,drum,bonus,result};app.innerHTML=`<section class="screen">${(views[page]||home)()}</section>`;app.focus({preventScroll:true})}
function home(){return `<div class="home-top"><div class="home-copy"><h1 class="hero-title">Trust absolutely<span>nobody.</span></h1><p class="hero-description">One different word. A room full of suspects.<br>Think you know your friends?</p><div class="hero-actions">${btn('setup','Start <span class="arrow">↗</span>')}</div><p class="legal-note"><span>This service is developed and maintained by <a href="https://mas0ng.com?from=devLink&product=imposter" target="_blank" rel="noopener noreferrer">mas0ng.com</a>.</span><span>By continuing, you confirm that you have read and agree to the <a href="https://mas0ng.com/legal/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</a> and <a href="https://mas0ng.com/legal/terms" target="_blank" rel="noopener noreferrer">Terms of Service</a>, which apply to this service.</span></p></div><div class="hero-art"><div class="orbit"></div><span class="doodle one">✦</span><span class="doodle two">?</span><span class="doodle three">✧</span><div class="secret-card"><span class="card-label">LOOKING INNOCENT?</span><div class="mask mint-mask"></div><strong>Same word.</strong></div><div class="secret-card purple"><span class="card-label">ACTING SUSPICIOUS?</span><div class="mask"></div><strong>Different word.</strong></div><div class="floating-label"><span>✦</span> Someone has a little secret.</div></div></div>`}
function tile(a,i,t,d,c){return `<button class="feature-tile" data-action="${a}"><span class="feature-icon ${c}">${i}</span><span><strong>${t}</strong><small>${d}</small></span><span class="arrow">↗</span></button>`}
function setupOld(){let s=state.settings;return `${heading('WHO IS PLAYING?','Add your players.','Enter at least three names to continue.')}<div class="setup-grid"><div class="panel"><div class="panel-title"><h2>The usual suspects</h2><span class="count-tag">${namedPlayers()} named</span></div><div class="player-list">${state.players.map((p,i)=>`<div class="player-row">${avatar(p)}<input data-name="${p.id}" maxlength="24" value="${esc(p.name)}" placeholder="Player ${i+1}" aria-label="Player ${i+1} name"><button class="remove" data-remove="${p.id}" aria-label="Remove player">×</button></div>`).join('')}${state.players.length<15?btn('add','＋ Add player','add-player'):''}</div></div><div class="panel"><div class="panel-title"><h2>Round options</h2><span>✦</span></div><div class="field-grid"><label>Difficulty<select data-set="difficulty">${['mixed','easy','medium','hard'].map(x=>`<option ${s.difficulty===x?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></label><label>Imposters<select data-set="imposters"><option value="1">1 imposter</option><option value="2" ${state.players.length<6?'disabled':''} ${s.imposters===2?'selected':''}>2 imposters</option></select></label></div><button class="setting-link" data-action="categories"><span>🗂️ &nbsp; Word packs<small>${state.categories.length} selected · ${eligible().length} pairs</small></span><span class="arrow">›</span></button></div></div><div class="setup-footer"><p>${namedPlayers()<3?`Add ${3-namedPlayers()} more name${3-namedPlayers()===1?'':'s'} to continue.`:'Ready when you are.'}</p>${btn('start','Let’s play ✦','primary',eligible().length&&namedPlayers()>=3?'':'disabled')}</div>`}
function categories(){let list=cats().filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));return `${btn('back','← Back','back-link')}${heading('PICK YOUR FLAVOUR','A little something for everyone.',`${db.pairs.length} hand-matched pairs. Never random.`)}<div class="toolbar"><input id="search" placeholder="Search word packs…" value="${esc(query)}">${btn('all','Select all','ghost')}${btn('none','Clear all','ghost')}${btn('packs','＋ Custom packs','secondary')}</div><div class="category-grid">${list.map(c=>`<button class="category-card" data-cat="${esc(c.id)}" aria-pressed="${state.categories.includes(c.id)}"><span class="emoji">${c.emoji}</span><span class="check">${state.categories.includes(c.id)?'✓':''}</span><strong>${esc(c.name)}</strong><small>${pairs().filter(p=>p.category===c.id).length} pairs</small></button>`).join('')||'<div class="empty">No matching packs.</div>'}</div><div class="category-footer"><p>${state.categories.length?`${eligible().length} pairs match your difficulty.`:'Select a pack to start.'}</p>${btn('back','Save my picks ✓','primary',state.categories.length?'':'disabled')}</div>`}
function dots(){return `<div class="progress-dots">${state.players.map((_,i)=>`<i class="${i<round.i?'done':i===round.i?'current':''}"></i>`).join('')}</div>`}
function pass(){let p=state.players[round.i];return `<div class="center-screen">${dots()}<div class="pass-card">${avatar(p,true)}<span class="eyebrow">PASS THE DEVICE TO</span><h2>${esc(name(p))}</h2>${btn('identity',`I’m ${esc(name(p))} →`)}</div></div>`}
function word(){return `<div class="center-screen">${dots()}<div id="wordbox" class="word-card hidden-word"><div id="secret"><div class="mask" style="margin:auto"></div><p>Ready for your word?</p></div></div><div class="word-actions">${state.settings.hold?`<button id="hold" class="primary hold-button">Hold to reveal ◉</button>`:btn('reveal','Reveal my word ✦')}</div></div>`}
function show(){let p=state.players[round.i],im=round.imposters.includes(p.id);$('#secret').innerHTML=`<div class="eyebrow">${im&&state.settings.tellRole?'YOU’RE THE IMPOSTER 👀':'YOUR SECRET WORD'}</div><div class="secret-word">${esc(im?round.bad:round.good)}</div><p>Remember it. Don’t let anyone else see it.</p>`;$('#wordbox').classList.remove('hidden-word');const actions=document.querySelector('.word-actions');if(!state.settings.hold&&actions)actions.innerHTML=btn('next','Hide & pass it on →')}
function hide(){let b=$('#wordbox');if(!b)return;b.classList.add('hidden-word');$('#secret').innerHTML='<div class="mask" style="margin:auto"></div><p>Safely hidden.</p>'}
function order(){return state.players.map((_,i)=>state.players[(round.speaker+i)%state.players.length])}
function discussionOld(){return `<div class="center-screen"><div class="eyebrow">EVERYONE HAS THEIR WORD 👀</div><h1>Now, act natural.</h1><p class="muted">Give a clue. Hear everyone out. Find the word that doesn’t belong.</p><div class="discussion-banner"><div><span class="round-label">CLUE ROUND ${round.clue} OF ${state.settings.clueRounds}</span><strong>🎤 ${esc(name(order()[0]))}, you’re up first.</strong><p>Go in order. One clue each. Don’t say your secret word.</p></div>${btn('timer',`▷ <span id="clock">${clock()}</span>`,'secondary timer')}</div><div class="player-grid">${order().map((p,i)=>`<div class="person-card">${avatar(p)}<strong>${esc(name(p))}</strong><small>${i?'CLUE '+(i+1):'FIRST CLUE'}</small></div>`).join('')}</div><div class="button-row">${round.clue<state.settings.clueRounds?btn('clue','Next clue round →','secondary'):''}${btn(state.settings.voting?'vstart':'drum',state.settings.voting?'Time to vote →':'Reveal imposter ✦')}</div></div>`}
function votepass(){let p=state.players[round.voter];return `<div class="center-screen"><div class="eyebrow">SECRET BALLOT</div><h1>Time to point fingers.</h1><p class="muted">Your vote is between you and this screen.</p>${dots()}<div class="pass-card">${avatar(p,true)}<span class="eyebrow">PASS THE DEVICE TO</span><h2>${esc(name(p))}</h2>${btn('videntity',`I’m ${esc(name(p))} →`)}</div></div>`}
function vote(){let p=state.players[round.voter],c=state.players.filter(x=>x.id!==p.id);return `<div class="center-screen"><div class="eyebrow">${esc(name(p))}’S PRIVATE VOTE</div><h1>Who’s a little too innocent?</h1><p class="muted">Trust your gut. You can’t vote for yourself.</p><div class="player-grid">${c.map(x=>`<button class="person-card ${round.pick===x.id?'selected':''}" data-vote="${x.id}">${avatar(x)}<strong>${esc(name(x))}</strong><small>${round.pick===x.id?'YOUR PICK':'LOOKS SUSPICIOUS'}</small></button>`).join('')}</div>${btn('lock','Lock in my vote ✓','primary',round.pick?'':'disabled')}</div>`}
function votes(){return `<div class="center-screen"><div class="eyebrow">THE VOTES ARE IN…</div><h1>The room has spoken.</h1><p class="muted">The group suspects ${round.accused.map(x=>esc(name(state.players.find(p=>p.id===x)))).join(' & ')}.</p>${bars()}${btn('drum','Reveal imposter ✦')}</div>`}
function bars(){let max=Math.max(1,...Object.values(round.counts));return `<div class="result-bars">${state.players.slice().sort((a,b)=>round.counts[b.id]-round.counts[a.id]).map(p=>`<div class="result-row">${avatar(p)}<strong>${esc(name(p))}</strong><div class="bar-track"><div class="bar-fill" style="width:${round.counts[p.id]/max*100}%"></div></div><span>${round.counts[p.id]}</span></div>`).join('')}</div>`}
function drum(){return `<div class="center-screen"><div class="eyebrow">THE MOMENT OF TRUTH</div><h1>The imposter${round.imposters.length>1?'s are':' is'}…</h1><div class="drum-stage"><span class="eyebrow">TRUST ABSOLUTELY NOBODY.</span><div class="drum-name" id="drummer">?</div><div class="drum-dots">● ● ●</div></div></div>`}
function bonus(){let p=state.players.find(p=>p.id===round.bonus[round.bi]);return `<div class="center-screen"><span class="pill warning">CAUGHT… BUT NOT QUITE FINISHED.</span><h1>One last chance, ${esc(name(p))}.</h1><p class="muted">What do you think everyone else’s word was?</p><div class="pass-card">${avatar(p,true)}<form id="bonusform" class="bonus-form"><label>Your guess<input name="guess" required maxlength="60" autocomplete="off"></label><button class="primary">Lock in guess →</button></form>${btn('skip','Skip this guess','ghost')}</div></div>`}
function result(){let imp=state.players.filter(p=>round.imposters.includes(p.id)),names=imp.map(p=>esc(name(p))).join(' & ');return `<div class="center-screen"><h1 class="imposter-final">The imposter was ${names}</h1><div class="button-row">${btn('again','Another round ↗')}${btn('end','End','secondary')}</div></div>`}
function start(custom){state.players=state.players.filter(p=>p.name.trim()).map((p,i)=>({...p,color:COLORS[i%COLORS.length]}));if(state.players.length<3)return toast('Add at least three names first.');state.settings.imposters=Math.min(Math.max(1,+state.settings.imposters||1),Math.max(1,Math.floor((state.players.length-1)/2)));let list=eligible();if(!custom&&!list.length)return toast('Select at least one word pack first.');let fresh=list.filter(p=>!state.history.includes(p.id));let pair=custom||((fresh.length?fresh:list)[Math.floor(Math.random()*(fresh.length?fresh:list).length)]);let flip=Math.random()<.5;round={good:flip?pair.word2:pair.word1,bad:flip?pair.word1:pair.word2,imposters:shuffle(state.players).slice(0,state.settings.imposters).map(p=>p.id),i:0,speaker:Math.floor(Math.random()*state.players.length),clue:1,voter:0,pick:null,votes:{},counts:{},accused:[],bonus:[],bi:0};state.round++;if(!custom){state.history=[...state.history.filter(x=>x!==pair.id),pair.id].slice(-1000)}save();page='pass';celebrate();render()}
function shuffle(a){let x=a.slice();for(let i=x.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function finishVotes(){round.counts=Object.fromEntries(state.players.map(p=>[p.id,0]));Object.values(round.votes).forEach(x=>round.counts[x]++);round.accused=state.players.slice().sort((a,b)=>round.counts[b.id]-round.counts[a.id]).slice(0,round.imposters.length).map(p=>p.id);page='votes';render()}
function reveal(){round.bonus=[];score();page='result';render();celebrate()}
function score(){if(round.scored)return;round.scored=true;state.players.forEach(p=>{let add=0;if(state.settings.scores){if(round.votes[p.id]&&round.imposters.includes(round.votes[p.id]))add+=SCORE.vote;if(round.imposters.includes(p.id)&&!round.accused.includes(p.id))add+=SCORE.survive;if(round.correct?.includes(p.id))add+=SCORE.bonus}p.score+=add});save()}
function clock(){return `${Math.floor(time/60)}:${String(time%60).padStart(2,'0')}`}
function celebrate(){let box=$('#confetti');box.innerHTML='';const colours=['#8060d6','#eda5ba','#78b890','#f0c764','#82b8df','#f2a96f'];for(let i=0;i<92;i++){let e=document.createElement('i');e.className='confetti-piece';let size=5+Math.random()*8,shape=i%7===0?'50%':i%9===0?'2px':'1px';e.style.cssText=`left:${42+Math.random()*16}%;top:${42+Math.random()*12}%;--drift:${Math.random()*900-450}px;--lift:${-(130+Math.random()*260)}px;--turn:${Math.random()*1080-540}deg;--size:${size}px;--delay:${Math.random()*110}ms;--duration:${1500+Math.random()*1200}ms;background:${colours[i%colours.length]};border-radius:${shape}`;box.append(e)}setTimeout(()=>box.innerHTML='',3600)}
function open(type){modal.dataset.type=type;modal.innerHTML=modalHTML(type);modal.showModal()}
function close(){modal.close()}
function modalHTML(t){if(t==='how')return box('How it works',`<div class="how-step"><span class="feature-icon lavender">1</span><div><strong>Get your secret.</strong><p>Everyone gets the same word except the imposter, who gets a related one.</p></div></div><div class="how-step"><span class="feature-icon peach">2</span><div><strong>Drop a clue.</strong><p>Give a clue without saying your word. Listen for a different one.</p></div></div><div class="how-step"><span class="feature-icon mint">3</span><div><strong>Vote privately.</strong><p>Pass the device and lock in a secret vote. Then enjoy the reveal.</p></div></div>`,btn('close','Got it. Trust nobody.'));
if(t==='settings')return box('Your kind of chaos.',`<div class="settings-columns">${toggle('haptics','Haptic feedback','On supported devices.')}${toggle('hold','Hold to reveal','Release to hide instantly.')}${toggle('tellRole','Tell imposter their role','Let them know they are different.')}${toggle('voting','Private voting','Point fingers, secretly.')}${toggle('scores','Keep scores','For the competitive ones.')}${toggle('bonus','Imposter bonus guess','One last chance.')}</div>`,btn('close','All set ✓'));
if(t==='custom')return box('An inside job.',`<form id="customform" class="custom-form"><div class="field-grid"><label>Normal word<input name="good" required maxlength="60" placeholder="School"></label><label>Imposter word<input name="bad" required maxlength="60" placeholder="College"></label></div><button class="primary">Use these words →</button></form>`);
if(t==='packs')return box('Your words. Their problem.',`<p class="modal-subtitle">Save related pairs, one per line: <strong>School | College</strong></p><form id="packform" class="custom-form"><label>Pack name<input name="name" required maxlength="40"></label><label>Related pairs<textarea name="pairs" rows="5" required placeholder="School | College&#10;Pizza | Burger"></textarea></label><button class="primary">Save word pack ＋</button></form>`);
return box('Leave this round?',`<p class="modal-subtitle">The unfinished round will end. Your players and scores are saved.</p>`,btn('close','Keep playing','secondary')+btn('confirmend','End round','danger'))}
function box(t,b,a=''){return `<div class="modal-heading"><h2 id="modal-title">${t}</h2><button class="icon-button" data-action="close">×</button></div>${b}<div class="modal-actions">${a}</div>`}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;let a=b.dataset.action;if(a){if(actions[a])actions[a]();return}if(b.dataset.toggle){state.settings[b.dataset.toggle]=!state.settings[b.dataset.toggle];save();if(modal.open)modal.innerHTML=modalHTML(modal.dataset.type);else render();return}if(b.dataset.remove){state.players=state.players.filter(p=>p.id!==b.dataset.remove);if(state.players.length<6)state.settings.imposters=1;save();render();return}if(b.dataset.cat){let x=b.dataset.cat;state.categories=state.categories.includes(x)?state.categories.filter(c=>c!==x):[...state.categories,x];save();render();return}if(b.dataset.vote){round.pick=b.dataset.vote;render()}});
const actions={home(){if(round&&page!=='result')open('quit');else{page='home';render()}},setup(){page='setup';render()},categories(){back=page;page='categories';render()},back(){page=back;render()},how(){open('how')},settings(){open('settings')},custom(){open('custom')},packs(){open('packs')},close,confirmend(){close();round=null;page='home';render()},all(){state.categories=cats().map(c=>c.id);save();render()},none(){state.categories=[];save();render()},add(){let n=state.players.length;if(n<15){state.players.push({id:id(),name:'',score:0,color:COLORS[n%6]});save();render()}},start(){start()},identity(){page='word';render()},reveal(){show()},next(){hide();round.i++;if(round.i<state.players.length)page='pass';else{round.unlockAt=Date.now()+5000;clearTimeout(revealTimer);revealTimer=setTimeout(()=>{if(page==='discussion')render()},5050);page='discussion'}render()},clue(){round.clue++;time=120;page='discussion';render()},timer(){if(timer){clearInterval(timer);timer=null;return}timer=setInterval(()=>{if(--time<0){clearInterval(timer);timer=null;time=0;toast('Time is up!')}let x=$('#clock');if(x)x.textContent=clock()},1000)},vstart(){round.voter=0;page='votepass';render()},videntity(){page='vote';render()},lock(){if(!round.pick)return;round.votes[state.players[round.voter].id]=round.pick;round.pick=null;round.voter++;if(round.voter<state.players.length)page='votepass';else finishVotes();render()},drum(){reveal()},skip(){round.bi++;if(round.bi>=round.bonus.length){score();page='result'}render()},again(){start()},end(){round=null;page='home';render()}};
actions.clearplayers=()=>{state.players=[];save();render()};
document.addEventListener('input',e=>{if(e.target.dataset.name){let p=state.players.find(p=>p.id===e.target.dataset.name);p.name=e.target.value;save()}if(e.target.id==='search'){query=e.target.value;render();$('#search').focus()}});
document.addEventListener('change',e=>{let k=e.target.dataset.set;if(k){state.settings[k]=k==='imposters'?+e.target.value:e.target.value.toLowerCase();save();render()}});
document.addEventListener('submit',e=>{e.preventDefault();let d=new FormData(e.target);if(e.target.id==='customform'){let a=d.get('good').trim(),b=d.get('bad').trim();if(a&&b&&a.toLowerCase()!==b.toLowerCase()){close();start({word1:a,word2:b})}return}if(e.target.id==='packform'){let ps=d.get('pairs').split('\n').map(x=>x.split('|').map(y=>y.trim())).filter(x=>x.length===2&&x[0]&&x[1]).map(x=>({word1:x[0].slice(0,60),word2:x[1].slice(0,60),difficulty:'medium'}));if(ps.length){let p={id:'custom:'+id(),name:d.get('name').trim().slice(0,40),pairs:ps};state.packs.push(p);state.categories.push(p.id);save();close();page='categories';render()}return}if(e.target.id==='bonusform'){let p=round.bonus[round.bi],g=d.get('guess').trim().toLowerCase();if(g===round.good.toLowerCase()){round.correct=[...(round.correct||[]),p]}round.bi++;if(round.bi>=round.bonus.length){score();page='result'}render()}});
document.addEventListener('pointerdown',e=>{if(e.target.id==='hold')show()});document.addEventListener('pointerup',e=>{if(e.target.id==='hold')hide()});window.addEventListener('blur',hide);document.addEventListener('visibilitychange',()=>document.hidden&&hide());
fetch('./words.json').then(r=>r.json()).then(x=>{const excluded=new Set(['Famous People','Artists','Characters']);const footballPeople=new Set(['Messi','Neymar','Haaland','Saka','Bellingham','Salah','Xavi','Zidane']);db={categories:x.categories.filter(c=>!excluded.has(c.id)),pairs:x.pairs.filter(p=>!excluded.has(p.category)&&!footballPeople.has(p.word1))};let valid=new Set(cats().map(x=>x.id));const defaultPacks=['Food','Drinks','Fast Food','Video Games','Tabletop','Animals','Countries','Sports','Football','Music','Transport','School','Jobs','Everyday Objects'];state.categories=state.categories===null||state.categories.length>18?defaultPacks.filter(x=>valid.has(x)):state.categories.filter(x=>valid.has(x));save();render()}).catch(()=>{app.innerHTML='<div class="loading"><h2>Word packs could not load.</h2><p>Keep words.json beside index.html.</p></div>'});

// Refresh the DiceBear image after a short pause, rather than on every keystroke.
document.addEventListener('input',e=>{if(!e.target.dataset.name)return;clearTimeout(nameTimer);const input=e.target;nameTimer=setTimeout(()=>{const image=input.closest('.player-row')?.querySelector('.avatar img');if(image)image.src=input.value.trim()?`https://api.dicebear.com/10.x/adventurer-neutral/svg?seed=${encodeURIComponent(input.value.trim())}`:'./blankpfp.jpg';const startButton=document.querySelector('[data-action="start"]');if(startButton)startButton.disabled=!allPlayersNamed();const hint=document.querySelector('.setup-footer p');if(hint)hint.textContent=allPlayersNamed()?'Ready when you are.':'Add a name to every player slot.';},450)});

function setup(){const ready=allPlayersNamed(),maxImposters=Math.max(1,Math.floor((state.players.length-1)/2));state.settings.imposters=Math.min(Math.max(1,+state.settings.imposters||1),maxImposters);return `${heading('','Add your players.','Fill in every player name to continue.')}<div class="setup-grid"><div class="panel"><div class="panel-title"><h2>The usual suspects</h2></div><div class="player-list">${state.players.map((p,i)=>`<div class="player-row">${avatar(p)}<input data-name="${p.id}" maxlength="24" value="${esc(p.name)}" placeholder="Player ${i+1}" aria-label="Player ${i+1} name"><button class="remove" data-remove="${p.id}" aria-label="Remove player">×</button></div>`).join('')}${state.players.length<15?btn('add','＋ Add player','add-player'):''}${state.players.length?btn('clearplayers','Clear all','add-player'):''}</div></div><div class="panel"><div class="panel-title"><h2>Round options</h2></div><label class="imposter-field">Imposters<input class="imposter-input" type="number" data-set="imposters" min="1" max="${maxImposters}" step="1" value="${state.settings.imposters}" aria-describedby="imposter-help"><small id="imposter-help" class="muted">Choose between 1 and ${maxImposters}.</small></label><button class="setting-link" data-action="categories"><span>🗂️ &nbsp; Word packs<small>${state.categories.length} selected · ${eligible().length} pairs</small></span><span class="arrow">›</span></button></div></div><div class="setup-footer"><p>${ready?'Ready when you are.':'Add a name to every player slot.'}</p>${btn('start','Let’s play','primary',ready?'':'disabled')}</div>`}

function discussion(){const locked=Date.now()<(round.unlockAt||0),left=Math.max(0,Math.ceil(((round.unlockAt||0)-Date.now())/1000));return `<div class="center-screen"><p class="muted">Give a clue. Hear everyone out. Find the word that doesn’t belong.</p><div class="player-grid discussion-players">${order().map(p=>`<div class="person-card">${avatar(p)}<strong>${esc(name(p))}</strong></div>`).join('')}</div><div class="button-row">${btn('drum','Reveal imposter ✦','primary',locked?'disabled':'')}</div><p class="reveal-wait">${locked?`Reveal unlocks in ${left} seconds.`:''}</p></div>`}
